### ISSUE TITLE
opam wix failing on "which" due to path "C:\cygdrive\c...."

### ISSUE THREAD

**Issue by maroneze** [OCamlPro/opam-wix#2]
I just tried using opam-wix, but I'm having some issues with the command.

I'm using a Cygwin installed from the [OCaml for Windows](https://fdopen.github.io/opam-repository-mingw/installation/) website. It is installed in `C:\Ocaml64`, I have the `util-linux` package installed (2.33.1-2), and I installed Wix 3.11 in `C:\Program Files (x86)\WiX Toolset v3.11` (default directory).

I set `WIXPATH` as `/cygdrive/c/Program Files (x86)/WiX Toolset v3.11` in the system properties, and it seems correct: if I run `ls "$WIXPATH"` in Cygwin, it does list the content of the directory (which contains a `bin` directory with, among others, `candle.exe`).

However, when I run `opam wix <pkg>`, it fails with a weird path:

```
<><> Initialising Opam ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] # path        ~
        # command     C:\OCaml64\bin\which.exe C:\cygdrive\c\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe
        # exit-code   1
        # env-file    C:\OCaml64\tmp\opam-lsl-9312\which-ccabea-9312-42bb52.env
        # output-file C:\OCaml64\tmp\opam-lsl-9312\which-ccabea-9312-42bb52.out
        ### output ###
        # /usr/bin/which: no C:\cygdrive\c\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe in
        (/home/lsl/.opam/plugins/bin:/home/lsl/.opam/4.14.0+mingw64c/bin:/usr/x86_64-w64-mingw32/sys-root/mingw/bin:/usr/local/bin:/usr/bin:/cygdrive/c/Windows/system32:/cygdrive
/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Windows/System32/OpenSSH:/c[...]
```

Somehow, the path `/cygdrive/c/...` was converted to `C:\cygdrive\c\...`, which obviously fails.

I tried setting WIXPATH to other values, such as `C:/Program Files (x86)/WiX Toolset v3.11`, but it stills gets "normalized" to the same `C:\cygdrive\c\...`.

Should I change my Cygwin setup, install a different OCaml compiler, or something else? I'm not sure how to further debug the issue.

**Comment by hernoufM** [comment]
Hi @maroneze, could you show the full command that produced this problem?

**Comment by maroneze** [comment]
I just installed `headache` (as an example of a very simple OCaml application, to test opam-wix) and then ran `opam wix headache`. But it happens with any package I choose (`opam wix frama-c`, `opam wix why3`, etc), since the issue is during initialization.

I also tried being more explicit, e.g. `opam wix headache --binary headache --wix-path "$WIXPATH"`, but it doesn't change anything.

Expanding the variable, I can also try:

    opam wix headache --binary headache --wix-path "/cygdrive/c/Program Files (x86)/WiX Toolset v3.11"

But I still get:

```
 /usr/bin/which: no C:\cygdrive\c\Program Files (x86)\WiX Toolset v3.11\candle.exe in
        (/home/lsl/.opam/plugins/bin:/home/lsl/.opam/4.14.0+mingw64c/bin:/usr/x86_64-w64-mingw32/sys-root/mingw/bin:/usr/local/bin:/usr/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerS
hell/v1.0:/cygdrive/c/Windows/System32/OpenSSH:/cygdr[...]
```

**Comment by rjbou** [comment]
Are you launching `opam-wix` from a cygwin or cmd/powershell terminal?
We noticed something weird: `which` path is a Windows path while it should be an unix path.
We developed and tested the tool only under cygwin, not having a setup resulting from ocaml for windows.
In any case, it highlighted a needed patch for path conversion, but it is not sure that it'll fix this issue.

**Comment by maroneze** [comment]
I'm running it from the OCaml64 terminal shortcut created by Ocaml for Windows, which is Cygwin, but with a MinGW compiler (in case this changes anything).

If I do `file /usr/bin/which`, it shows `PE32+ executable (console) x86-64, for MS Windows, 8 sections`, in case it helps.

I don't think I've user used Cygwin without having it and opam both installed with OCaml for Windows. Did you start from the Cygwin setup executable in a brand-new directory, and compiled a purely-Cygwin OCaml compiler? How do you get opam installed in that case? The [opam installation](https://opam.ocaml.org/doc/Install.html) page has no binaries for Windows, but it links to [OCaml for Windows](https://fdopen.github.io/opam-repository-mingw/), so I assumed it was the "only" way to install OCaml on Windows.

**Comment by maroneze** [comment]
Indeed, now I can no longer install it, since it requires `os = "cygwin"`, but my `opam config list` shows:

```
os                win32                     # Inferred from system
os-distribution   cygwinports               # Inferred from system
os-family         windows                   # Inferred from system
```

I'll try installing a new opam in Cygwin from scratch.

**Comment by maroneze** [comment]
At the risk of sidetracking a bit too much, I wasn't able to install opam that easily: after installing Cygwin on `C:\Cygwin`, plus several "basic" packages (gcc, make, etc), 30 minutes after running `make cold` on opam, I got:

```
ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
./.duneboot.exe
/home/lsl/opam/src_ext/dune-local/dune.exe build --profile=release --root .  --promote-install-files -- opam-installer.install opam.install
File "src/stubs/libacl/opamlibACL.ml", line 1:
Warning 70 [missing-mli]: Cannot find interface file.
File "src_ext/dose3/src/common/dune", line 16, characters 0-255:
16 | (rule
17 |  (targets gitVersionInfo.ml)
18 |  ; Ensures the hash update whenever a source file is modified ;
19 |  (deps
20 |   (source_tree %{workspace_root}/.git)
21 |   (:script get-git-info.mlt))
22 |  (action
23 |   (with-stdout-to
24 |    %{targets}
25 |    (run %{ocaml} unix.cma %{script}))))
Cannot load required shared library dllunix.
Reason: dllunix.so: dynamic loading not supported on this platform.
make[1]: *** [Makefile:144: build-opam] Error 1
```

By the way, would using a `msvc` port of OCaml for Windows allow opam-wix to be installed? I believe it would not be identified as `os = "cygwin"` even if running from Cygwin, since with MinGW it output `os = "win32"`, but if that might help, I could try doing that (assuming I do find a way to install OCaml with MSVC, as seen in some 2019 discussions).

**Comment by rjbou** [comment]
> Indeed, now I can no longer install it, since it requires `os = "cygwin"`, but my `opam config list` shows:
> 
> ```
> os                win32                     # Inferred from system
> os-distribution   cygwinports               # Inferred from system
> os-family         windows                   # Inferred from system
> ```
> 
> I'll try installing a new opam in Cygwin from scratch.

You can try to pin edit it and change constraint to `os = win32`

**Comment by rjbou** [comment]
We will maybe need to update that, to have something compliant with cygwin & msvc.

**Comment by maroneze** [comment]
Ok, I managed to compile and install `opam`, now `opam init` fails, once again, due to path issues:

```
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "Curl failed: \"/cygdrive/c/Windows/system32/curl --write-out
        %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent opam/2.2.0~alpha -L -o /tmp/opam-34370-fa060e/index.tar.gz.part --
        https://opam.ocaml.org/index.tar.gz\" exited with code 23")
[ERROR] Initial download of repository failed.
```

Now, after debugging it, I understood the cause:
- my Cygwin didn't have the `curl` package installed;
- but since `C:\windows\system32` is in the PATH (I didn't add it explicitly, I'm fairly sure this is standard), Cygwin found the binary anyway, and usedit;
- but the `curl.exe` that comes with Windows is a *native Windows binary*, so of course it couldn't understand the `/tmp/` path, and failed writing to a non-existing directory.
- After manually testing it with `C:\Cygwin\tmp` and seeing it worked, I thought of installing Cygwin's version of `curl`;
- Then, re-running `opam init` worked (at least the download part; it's still compiling and installing the rest).

But then, I really wonder how you managed to get opam working under Cygwin; did you start from a predefined list of packages to install (including `flexdll`, `curl`, etc)? Or is your PATH variable setup differently, so that it avoids such issues?

I'm afraid such extended details about setting up the environment would be needed to ensure opam-wix is usable (unless such instructions are already available somewhere).

Should I consider adding these steps (as I find them, to ensure I don't forget anything) to opam-wix's README? Or to another file? Or maybe there is already an up-to-date Cygwin tutorial somewhere that I could refer to?

**Comment by rjbou** [comment]
For our install, it was installing cygwin packages. And yes, windows curl is found in path, but not compliant (even if it understands the path, there is other differences).
On external dependencies, for opam itself, with `git`, `make`, `tar`, `diffutils`, and `patch` you *should* have everything. @hernoufM do you see other steps to point?
We'll need to add/update opam-wix documentation indeed. Maybe port to opam documentation too (for 2.1). 

Opam 2.2 will have simpler install on Windows.

**Comment by hernoufM** [comment]
You should install curl to make cygwin use its own curl with :
```bash
lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg
install apt-cyg /bin
apt-cyg install curl
```

**Comment by maroneze** [comment]
Ok, using the "pure Cygwin" version I don't have any path issues, thank you.
